### ISSUE TITLE
Question: Is this being used on production?

### ISSUE THREAD

**Issue by whiteboardmonk** [soheilpro/sqlmon#1]
Stumbled upon this on HN. Wanted to check the following:
- What kind of performance impact would this have on the SQL server
- What typical trace duration would you recommend?
- Lastly, the ideal expectation is to run this hourly?

**Comment by soheilpro** [comment]
Yes, we regularly use this tool (in conjunction with [sqltop](https://github.com/soheilpro/sqltop)) to find the most resource consuming queries in our services.

This tool uses the same built-in SQL Server [tracing functionality](https://docs.microsoft.com/en-us/sql/relational-databases/sql-trace/sql-trace) that [SQL Server Profiler](https://docs.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler) uses. The 
performance impact is usually very low but it depends on your workload and hardware.

The frequency and the duration to run traces also depends on what you want to profile.

**Comment by whiteboardmonk** [comment]
Thanks @soheilpro for the reply and the tip for using `sqltop`
